package com.webank.wecross.stub.chainmaker.common;

import com.webank.wecross.stub.StubConstant;

public interface ChainMakerConstant {
    String CHAINMAKER_STUB_TYPE = "CHAINMAKER_PROPERTY_STUB_TYPE";
    String CHAINMAKER_CHAIN_ID = "CHAIN_ID";
    String CHAINMAKER_PROXY_NAME = StubConstant.PROXY_NAME;
    String CHAINMAKER_HUB_NAME = StubConstant.HUB_NAME;
    String CUSTOM_COMMAND_DEPLOY_CONTRACT = "DEPLOY_CHAINMAEKER_CONTRACT";
    String CUSTOM_COMMAND_UPGRADE_CONTRACT = "UPGRADE_CHAINMAEKER_CONTRACT";
    String CUSTOM_COMMAND_REGISTER_CONTRACT = "REGISTER_EXISTING_CONTRACT";
    String CHAINMAKER_CONTRACT_NAME = "CONTRACT_NAME";
    String CHAINMAKER_CONTRACT_ADDRESS = "CONTRACT_ADDRESS";
    String CHAINMAKER_CONTRACT_VERSION = "CONTRACT_VERSION";
    String CHAINMAKER_CONTRACT_RUNTIME_TYPE = "CONTRACT_RUNTIME_TYPE";
    String CHAINMAKER_ENDORSEMENTENTRY = "CHAINMAKER_ENDORSEMENTENTRY";
}
