chain_client:
  # 链ID
  chain_id: qctc003
  # 组织ID
  org_id: qctc003-org-id-001
  # 客户端用户私钥路径
  user_key_file_path: ./crypto-config/qctc003-org-id-001/user/qctc003-org-admin-001/qctc003-org-admin-001.tls.key
  user_crt_file_path: ./crypto-config/qctc003-org-id-001/user/qctc003-org-admin-001/qctc003-org-admin-001.tls.crt
  user_sign_key_file_path: ./crypto-config/qctc003-org-id-001/user/qctc003-org-admin-001/qctc003-org-admin-001.sign.key
  user_sign_crt_file_path: ./crypto-config/qctc003-org-id-001/user/qctc003-org-admin-001/qctc003-org-admin-001.sign.crt
  retry_limit: 10
  retry_interval: 500
  nodes:
  - node_addr: 192.168.14.127:12301
    conn_cnt: 10
    enable_tls: true
    trust_root_paths:
      - ./crypto-config/qctc003-org-id-001/ca
    tls_host_name: chainmaker.org
  archive:
    type: mysql
    dest: root:3.16:192.168.14.130:3306
    secret_key: xxx

  rpc_client:
    # grpc客户端最大接受容量(MB)
    max_receive_message_size: 16

  pkcs11:
    enabled: false # pkcs11 is not used by default

  # 交易结果是否订阅获取
  enable_tx_result_dispatcher: true

  ##连接池配置
  connPool:
    # 最大连接数
    maxTotal: 100
    # 最少空闲连接
    minIdle: 1
    #最大空闲连接
    maxIdle: 20
    #连接空闲最小保活时间，默认即为30分钟(18000000)，单位：ms
    minEvictableIdleTime: 350000
    #回收空闲线程的执行周期，单位毫秒。默认值60000ms（60s） ，-1 表示不启用线程回收资源，单位：ms
    timeBetweenEvictionRuns: 60000
    #没有空闲连接时，获取连接是否阻塞
    blockWhenExhausted: true
    #当没有空闲连接时，获取连接阻塞等待时间，单位：ms
    maxWaitMillis: 3000

